language: php
dist: xenial

# Since Xenial services are not started by default, we need to instruct it below to start.
services:
  - mysql
  
sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    
notifications:
  email:
    on_success: never
    on_failure: change

# Test main supported versions of PHP against latest WP.
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

# Clone repo to a maximum depth of 2 commits
git:
  depth: 2
  
# safelist
branches:
  only:
  - master
  
env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  fast_finish: true
  include:
    - name: "PHP:7.4 - Coding standard check"
      php: 7.4
      env: WP_VERSION=latest WP_MULTISITE=0 RUN_PHPCS=1
    - name: "PHP:7.4 - Unit tests code coverage"
      php: 7.4
      env: WP_VERSION=latest WP_MULTISITE=0 RUN_CODE_COVERAGE=1
    - name: "PHP:7.4 - Unit tests using WordPress nightly"
      php: 7.4
      env: WP_VERSION=nightly WP_MULTISITE=0
  allow_failures:
    - php: 7.4
      env: WP_VERSION=nightly WP_MULTISITE=0 RUN_CODE_COVERAGE=1

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    # Remove Xdebug for a huge performance increase:
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ "$SNIFF" == "1" ]]; then
      composer install --no-suggest --no-interaction
    else
      composer global require --dev phpunit/phpunit ^6
    fi
  - which phpunit
  - |
    if [[ "$SNIFF" == "1" ]]; then
      vendor/bin/phpunit --version
    else
      phpunit --version
    fi
  # Install phpunuit test suite
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    
script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs
    fi
